# Generated by Django 3.2.14 on 2022-11-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slot',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
