# Generated by Django 3.2.14 on 2022-11-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0003_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
