# Generated by Django 3.2.14 on 2022-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0005_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='max_booking_per_time',
            field=models.IntegerField(default=1, help_text='how much booking can be book for each time.'),
        ),
    ]
