# Generated by Django 3.2.14 on 2022-11-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0006_bookingsettings_max_booking_per_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingSettings',
            new_name='BookingSetting',
        ),
    ]
