# Generated by Django 4.1.1 on 2023-02-21 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeddingApp', '0009_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Booking',
        ),
    ]
