# Generated by Django 4.1.1 on 2023-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0010_rename_appointment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
