# Generated by Django 4.1.1 on 2023-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0014_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
