# Generated by Django 4.1.1 on 2023-03-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0015_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
