# Generated by Django 4.1.1 on 2023-05-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0017_rename_date_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='WeddingApp.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
