# Generated by Django 4.1.1 on 2023-05-18 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeddingApp', '0020_alter_booking_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='name',
        ),
    ]
