# Generated by Django 4.1.1 on 2023-05-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0005_alter_product_image1_alter_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
