# Generated by Django 4.1.1 on 2023-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0006_product_description1_alter_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
