# Generated by Django 4.1.1 on 2023-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0008_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(blank=True),
        ),
    ]
